controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

lucky:
    path: /lucky
    controller: App\Controller\LuckyController::number